services:
  source_postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    networks:
      - fashion_network
    environment:
      POSTGRES_DB: source_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      #- ./source_db_init/init.sql:/docker-entrypoint-initdb.d/init.sql  # Initialization script
      - b0ef9f1d38a613cf6c004fa993f329962e169d7217f8bb5165ecddb650080027:/var/lib/postgresql/data

  Chroma-db:
    image: chromadb/chroma:latest
    ports:
      - "8000:8000"
    environment:
      - IS_PERSISTENT=TRUE
      - ALLOW_RESET=TRUE
      - ANONYMIZED_TELEMETRY=${ANONYMIZED_TELEMETRY:-TRUE}
    volumes:
      - ../../Chromadb/chroma-retail:/chroma/chroma
    networks:
      - fashion_network


networks:
  fashion_network:
    driver: bridge

volumes:
  b0ef9f1d38a613cf6c004fa993f329962e169d7217f8bb5165ecddb650080027:
    external: true