#version: '3'

services:
  source_postgres:
    image: postgres:latest
    ports:
      - "5433:5432"
    networks:
      - fashion_network
    environment:
      POSTGRES_DB: source_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - ./source_db_init/init.sql:/docker-entrypoint-initdb.d/init.sql

  chroma:
    image: chromadb/chromadb:latest
    ports:
      - "8080:8080"
    depends_on:
      - source_postgres
    environment:
      CHROMA_DB_HOST: db
      CHROMA_DB_USER: myuser
      CHROMA_DB_PASSWORD: mypassword
      CHROMA_DB_NAME: mydb
    volumes:
      - ./chromadata:/app/data
    networks:
      - fashion_network


networks:
  fashion_network:
    driver: bridge

    

