#version: '3'

services:
  source_postgres:
    image: postgres:latest
    ports:
      - "5433:5432"
    networks:
      - fashion_network
    environment:
      POSTGRES_DB: source_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - ./source_db_init/init.sql:/docker-entrypoint-initdb.d/init.sql

  chroma-db:
    build: .
    ports:
      - "8080:8080"
    environment:
      - CHROMA_DB_ALLOW_RESET=true
      - CHROMA_DB_ANONYMIZED_TELEMETRY=false
    networks:
      - fashion_network


networks:
  fashion_network:
    driver: bridge

    

